# Default set of loggers with output formats helpful when training models or
# running code fragments from Jupyter notebooks.
#
# Note that the config has a several placeholder variables starting with dollar
# sign and cannot be used directly to initialize loggers.

version: 1

root:
  level: NOTSET
  handlers: []

loggers:
  main:
    level: NOTSET
    handlers: [console, file]
  console:
    level: NOTSET
    handlers: [console]
  notebook:
    level: INFO
    handlers: [notebook]

handlers:
  console:
    class: logging.StreamHandler
    formatter: brief
    level: $console_level
  notebook:
    class: logging.StreamHandler
    formatter: minimal
    level: $console_level
  file:
    class: logging.FileHandler
    formatter: full
    level: $file_level
    filename: $logfile

formatters:
  full:
    format: >-
      %(asctime)s.%(msecs)03d|%(levelname)-8s|%(module)-16s
      line:%(lineno)-4d|
      %(message)s
    datefmt: "%Y/%m/%d %H:%M:%S"
  brief:
    format: "[%(asctime)s:%(levelname)-8s] %(message)s"
    datefmt: "%Y/%m/%d %H:%M:%S"
  minimal:
    format: "%(message)s"
    datefmt: "%H:%M:%S"